/*
 * Copyright (C) 2020 caidev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package GUI;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author caidev
 */
public class Visual extends javax.swing.JFrame {

	public static void MensajeError(String tituloPane, String errorMsg) {
		//===================================================================
		JOptionPane alerta = new JOptionPane(errorMsg);
		alerta.setMessageType(JOptionPane.ERROR_MESSAGE);
		//por defecto tiene un solo boton y toma el idioma del sistema.
		JDialog dialogo = alerta.createDialog(tituloPane);
		dialogo.setVisible(true);
		dialogo.setAlwaysOnTop(true);
		//===================================================================
	}
	
    /**
     * Creates new form Principal
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JTextField();
        btnCopiar = new javax.swing.JButton();
        txtMostrar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        jLabel1.setText("#CopyTextApp");

        jLabel2.setText("ingrese un mensaje:");

        btnCopiar.setText("Copiar");
        btnCopiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopiarActionPerformed(evt);
            }
        });

        jLabel3.setText("la copia del mensaje es:");

        btnClear.setText("Limpiar");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipalLayout.setHorizontalGroup(
        	panelPrincipalLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelPrincipalLayout.createSequentialGroup()
        			.addGroup(panelPrincipalLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(panelPrincipalLayout.createSequentialGroup()
        					.addGap(131)
        					.addComponent(jLabel3))
        				.addGroup(panelPrincipalLayout.createSequentialGroup()
        					.addGap(44)
        					.addGroup(panelPrincipalLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtMostrar, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)
        						.addComponent(txtMensaje, GroupLayout.PREFERRED_SIZE, 361, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(panelPrincipalLayout.createSequentialGroup()
        					.addGap(156)
        					.addComponent(jLabel2))
        				.addGroup(panelPrincipalLayout.createSequentialGroup()
        					.addGap(199)
        					.addComponent(btnCopiar))
        				.addGroup(panelPrincipalLayout.createSequentialGroup()
        					.addGap(190)
        					.addComponent(btnClear))
        				.addGroup(panelPrincipalLayout.createSequentialGroup()
        					.addGap(144)
        					.addComponent(jLabel1)))
        			.addContainerGap(67, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
        	panelPrincipalLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(panelPrincipalLayout.createSequentialGroup()
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(txtMensaje, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(btnCopiar)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel3)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(txtMostrar, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addComponent(btnClear))
        );
        panelPrincipal.setLayout(panelPrincipalLayout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnCopiarActionPerformed(java.awt.event.ActionEvent evt) {
    	if(txtMensaje.getText().equals("")) {
			MensajeError("Error al copiar.","El primer campo esta vacío.");
		}else {
	        String texto = txtMensaje.getText();
	        txtMostrar.setText("Copia: " + texto);
		}
    }                                         

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {
    	if(txtMensaje.getText().equals("")) {
			MensajeError("Advertencia.","No hay datos para limpiar.");
		}else {
	        txtMostrar.setText(null);
	        txtMensaje.setText(null);
		}
    }                                        

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCopiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtMensaje;
    private javax.swing.JTextField txtMostrar;
    // End of variables declaration                   
}
